'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3615
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   强类型资源类，用于查找本地化字符串等。
	''' </summary>
	' 此类是由 StronglyTypedResourceBuilder
	' 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
	' 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
	' (以 /str 作为命令选项)，或重新生成 VS 项目。
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   返回此类使用的缓存 ResourceManager 实例。
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   为使用此强类型资源类的所有资源查找
		'''   重写当前线程的 CurrentUICulture 属性。
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   查找类似 Main articles: History of science and Scientific revolution
		'''While descriptions of disciplined empirical investigations of the natural world exist from times at least as early as classical antiquity (for example, by Aristotle and Pliny the Elder), and scientific methods have been employed since the Middle Ages (for example, by Alhazen and Roger Bacon), the dawn of modern science is generally traced back to the early modern period during what is known as the Scientific Revolution of the 16th and 17th centuri [字符串的其余部分被截断]&quot;; 的本地化字符串。
		''' </summary>
		Friend ReadOnly Property Content() As String
			Get
				Return ResourceManager.GetString("Content", resourceCulture)
			End Get
		End Property

		Friend ReadOnly Property Icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Icon", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   查找类似 Personification of &quot;Science&quot; in front of the Boston Public Library 的本地化字符串。
		''' </summary>
		Friend ReadOnly Property ImageDescription() As String
			Get
				Return ResourceManager.GetString("ImageDescription", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   查找类似 Science History and Etymology 的本地化字符串。
		''' </summary>
		Friend ReadOnly Property Title() As String
			Get
				Return ResourceManager.GetString("Title", resourceCulture)
			End Get
		End Property
	End Module
End Namespace
